### ISSUE TITLE
Please ask is it possible to make the albionflipper part local and read Get native API?  I have successfully hooked up an albion_data for local

### ISSUE THREAD

**Issue by tuohao1125** [mattias-wiberg/AlbionFlipper#15]
Please ask is it possible to make the albionflipper part local and read Get native API?

I have successfully hooked up an albion_data for local

**Comment by mattias-wiberg** [comment]
Yes you can you just have to clone or fork the project and change the api url in js/main.js function fetchData. You need to run all the Albion data natives locally as well as the Albion data api.

**Comment by tuohao1125** [comment]
I modified the api url according to your method, but the operation failed.
I make sure my API is working.

Here is my modification
  var url = "https://127.0.0.1:8056/";
  var view = "api/v2/stats/" + type + "/";
  var location = [city. join(","), "black market"]
  var link = url + view + selected_items. join(",") + "? position=" + position. join(",") + "&qualities=" + qualities;
  //console.log("API link is "+link);
  printToConsole("Request API " + type + " with " + selected_items.length + " items" + " with quality " + quality + "\n");
  // Open a new connection, using a GET request on the URL endpoint
  Require. open('GET', link, true)
  ----------------------
  Chrome error message:
  main.js:584 Uncaught DOMException: Failed to perform 'open' on 'XMLHttpRequest': Invalid URL
    at fetchData (http://127.0.0.1:800/dashboard/flipper/js/main.js:584:11)
    at getPrices (http://127.0.0.1:800/dashboard/flipper/js/main.js:103:7)
    in HTMLButtonElement.onclick (http://127.0.0.1:800/dashboard/flipper/:234:100)
